//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/cloud/speech/v1/cloud_speech.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Google_Cloud_Speech_V1_SpeechClient, then call methods of this protocol to make API calls.
public protocol Google_Cloud_Speech_V1_SpeechClientProtocol {
  func recognize(_ request: Google_Cloud_Speech_V1_RecognizeRequest, callOptions: CallOptions?) -> UnaryCall<Google_Cloud_Speech_V1_RecognizeRequest, Google_Cloud_Speech_V1_RecognizeResponse>
  func longRunningRecognize(_ request: Google_Cloud_Speech_V1_LongRunningRecognizeRequest, callOptions: CallOptions?) -> UnaryCall<Google_Cloud_Speech_V1_LongRunningRecognizeRequest, Google_Longrunning_Operation>
  func streamingRecognize(callOptions: CallOptions?, handler: @escaping (Google_Cloud_Speech_V1_StreamingRecognizeResponse) -> Void) -> BidirectionalStreamingCall<Google_Cloud_Speech_V1_StreamingRecognizeRequest, Google_Cloud_Speech_V1_StreamingRecognizeResponse>
}

public final class Google_Cloud_Speech_V1_SpeechClient: GRPCClient, Google_Cloud_Speech_V1_SpeechClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the google.cloud.speech.v1.Speech service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Performs synchronous speech recognition: receive results after all audio
  /// has been sent and processed.
  ///
  /// - Parameters:
  ///   - request: Request to send to Recognize.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func recognize(_ request: Google_Cloud_Speech_V1_RecognizeRequest, callOptions: CallOptions? = nil) -> UnaryCall<Google_Cloud_Speech_V1_RecognizeRequest, Google_Cloud_Speech_V1_RecognizeResponse> {
    return self.makeUnaryCall(path: "/google.cloud.speech.v1.Speech/Recognize",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Performs asynchronous speech recognition: receive results via the
  /// google.longrunning.Operations interface. Returns either an
  /// `Operation.error` or an `Operation.response` which contains
  /// a `LongRunningRecognizeResponse` message.
  /// For more information on asynchronous speech recognition, see the
  /// [how-to](https://cloud.google.com/speech-to-text/docs/async-recognize).
  ///
  /// - Parameters:
  ///   - request: Request to send to LongRunningRecognize.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func longRunningRecognize(_ request: Google_Cloud_Speech_V1_LongRunningRecognizeRequest, callOptions: CallOptions? = nil) -> UnaryCall<Google_Cloud_Speech_V1_LongRunningRecognizeRequest, Google_Longrunning_Operation> {
    return self.makeUnaryCall(path: "/google.cloud.speech.v1.Speech/LongRunningRecognize",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Performs bidirectional streaming speech recognition: receive results while
  /// sending audio. This method is only available via the gRPC API (not REST).
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func streamingRecognize(callOptions: CallOptions? = nil, handler: @escaping (Google_Cloud_Speech_V1_StreamingRecognizeResponse) -> Void) -> BidirectionalStreamingCall<Google_Cloud_Speech_V1_StreamingRecognizeRequest, Google_Cloud_Speech_V1_StreamingRecognizeResponse> {
    return self.makeBidirectionalStreamingCall(path: "/google.cloud.speech.v1.Speech/StreamingRecognize",
                                               callOptions: callOptions ?? self.defaultCallOptions,
                                               handler: handler)
  }

}


// Provides conformance to `GRPCPayload` for request and response messages
extension Google_Cloud_Speech_V1_RecognizeRequest: GRPCProtobufPayload {}
extension Google_Cloud_Speech_V1_RecognizeResponse: GRPCProtobufPayload {}
extension Google_Cloud_Speech_V1_LongRunningRecognizeRequest: GRPCProtobufPayload {}
extension Google_Longrunning_Operation: GRPCProtobufPayload {}
extension Google_Cloud_Speech_V1_StreamingRecognizeRequest: GRPCProtobufPayload {}
extension Google_Cloud_Speech_V1_StreamingRecognizeResponse: GRPCProtobufPayload {}

